#+STARTUP: show3levels

This is my very cool [[https://github.com/doomemacs/doomemacs][Doom Emacs]] config. Feel free to copy whatevery you need for yours : )

* Personal info

#+BEGIN_SRC elisp
(setq user-full-name "Sergio Miguéns Iglesias"
      user-mail-address "yo@sergio.sh")
#+END_SRC

* Theme

#+BEGIN_SRC elisp
(setq doom-theme 'doom-gruvbox-light
      display-line-numbers-type 'relative
      fancy-splash-image "~/.local/share/emacs.png"
      alpha-background 0.1
      doom-font (font-spec :family "FiraCode Nerd Font" :size 13)
      confirm-kill-emacs nil)
#+END_SRC

* Org
** Settings

#+BEGIN_SRC elisp
(setq org-directory "~/sync/logseq/org/")
#+END_SRC

** Org-agenda

I use the =org-agenda= to track events and TODOs, and Nextcloud to sync them to my phone.

*** Settings

Do not show scheduled tasks if the deadline is in the same day, and do not warn me for upcoming deadlines, I can already see them!

#+BEGIN_SRC elisp
(setq org-deadline-warning-days 0
      org-agenda-skip-scheduled-if-deadline-is-shown t)
#+END_SRC

Also, show past events in grey. This is /vibecoded/ so I'm not 100% sure how it works.

#+BEGIN_SRC elisp
(defun sergio/org-agenda-dim-past-events ()
  "Dim past timed events in today's agenda view."
  (save-excursion
    (goto-char (point-min))
    (let ((now (decode-time (current-time))))
      (while (not (eobp))
        (let* ((line (buffer-substring (line-beginning-position) (line-end-position)))
               (time-match (string-match "\\([0-9]\\{1,2\\}\\):\\([0-9]\\{2\\}\\)" line)))
          (when time-match
            (let* ((hour (string-to-number (match-string 1 line)))
                   (min  (string-to-number (match-string 2 line)))
                   (past (or (< hour (nth 2 now))
                             (and (= hour (nth 2 now))
                                  (< min (nth 1 now))))))
              (when past
                (add-text-properties
                 (line-beginning-position) (line-end-position)
                 '(face (:foreground "gray50")))))))
        (forward-line 1)))))

(add-hook 'org-agenda-finalize-hook #'sergio/org-agenda-dim-past-events)
#+END_SRC

And make sure the agenda takes over the whole EMACS window.

#+BEGIN_SRC elisp
(setq org-agenda-window-setup 'other-tab
      tab-bar-show nil)
#+END_SRC

*** Keybindings

I don't like having to press =SPC o a a a= to get to the agenda list since it is the only thing I use.

#+BEGIN_SRC elisp
(map! :leader
      :desc "Org agenda"
      "o a" #'org-agenda-list)
#+END_SRC

*** Org-caldav

#+BEGIN_SRC elisp
(after! org-caldav
        (setq org-caldav-url "http://192.168.1.200:8000/remote.php/dav/calendars/sergio"
              org-caldav-calendar-id "main"
              org-caldav-inbox "/home/sergio/sync/logseq/org/dav-agenda.org"
              org-caldav-files '("~/sync/logseq/org/agenda.org"
                                 "~/sync/logseq/org/todo.org")
              org-icalendar-timezone "Europe/Madrid"
              org-icalendar-include-todo 'all
              org-caldav-sync-todo t
              org-export-with-broken-links t
              org-icalendar-use-deadline '(event-if-not-todo todo-due)
              org-icalendar-use-scheduled '(event-if-not-todo todo-start)
              org-caldav-todo-percent-states '((0   "PROJ")
                                               (0   "TODO")
                                               (10  "STRT")
                                               (100 "NO")
                                               (100 "DONE"))))
#+END_SRC

* Org-roam

Capture seconds too in the daily template, so that I get a new file per note I make (like in Logseq):

#+BEGIN_SRC elisp
(add-hook 'org-roam-buffer-postrender-functions
  (lambda () (org--latex-preview-region (point-min) (point-max))))
(after! org-roam
  (setq org-roam-dailies-capture-templates
    '(("d" "default" plain
       "%?"
       :target (file+head "%<%Y-%m-%d-%H-%M-%S>.org"
                          "#+title: %<%Y-%m-%d %H:%M:%S>\n")))))


(defun my/org-display-inline-images-fix (orig-fun &rest args)
  (let ((default-directory
          (if (bound-and-true-p org-roam-directory)
              org-roam-directory
            default-directory)))
    (apply orig-fun args)))

(advice-add 'org-display-inline-images :around #'my/org-display-inline-images-fix)
#+END_SRC

#+RESULTS:

And preview all images and latex equations:

#+BEGIN_SRC elisp
(add-hook 'org-mode-hook
  (lambda ()
    (when (and buffer-file-name
               (string-prefix-p (expand-file-name org-roam-directory)
                                (expand-file-name buffer-file-name)))
      (+zen/toggle 1)
      (org-latex-preview '(16))
      (org-display-inline-images t t))))

(setq org-roam-mode-sections
      '((org-roam-backlinks-section :unique t)
        org-roam-reflinks-section))
#+END_SRC

* Calendar
** Config calendar for Spain geek users

#+BEGIN_SRC elisp
(setq calendar-date-style 'iso
      calendar-week-start-day 1)
#+END_SRC

** Add a custom keybinding

#+BEGIN_SRC elisp
(map! :leader
      :desc "Open calendar"
      "o c" #'calendar)
#+END_SRC

** Disable all holidays and add custom ones:

#+BEGIN_SRC elisp
(setq holiday-general-holidays nil
      holiday-christian-holidays nil
      holiday-hebrew-holidays nil
      holiday-islamic-holidays nil
      holiday-bahai-holidays nil
      holiday-oriental-holidays nil)
(setq holiday-local-holidays
  '((holiday-fixed 1 1  "Año Nuevo")
    (holiday-fixed 1 6  "Epifanía del Señor")
    (holiday-easter-etc -3 "Jueves Santo")
    (holiday-easter-etc -2 "Viernes Santo")
    (holiday-fixed 5 1  "Fiesta del Trabajador")
    (holiday-fixed 5 2  "Fiesta de la Comunidad de Madrid")
    (holiday-fixed 5 15 "San Isidro Labrador")
    (holiday-fixed 8 15 "Asunción de la Virgen")
    (holiday-fixed 10 12 "Fiesta Nacional de España")
    (holiday-fixed 11 1 "Todos los Santos")
    (holiday-fixed 11 9 "Nuestra Señora de La Almudena")
    (holiday-fixed 12 6 "Día de la Constitución Española")
    (holiday-fixed 12 8 "Inmaculada Concepción")
    (holiday-fixed 12 25 "Natividad del Señor")))
#+END_SRC

* Mu4e
** Bookmarks

#+BEGIN_SRC elisp
(after! mu4e
  (setq mu4e-bookmarks
    '((:name "All archives"
       :query "maildir:/lonyelon@gmail.com/Archive/ or maildir:/yo@sergio.sh/Archive/"
       :key ?a)
      (:name "Inbox"
       :query "maildir:/lonyelon@gmail.com/Inbox/ or maildir:/yo@sergio.sh/Inbox/"
       :key ?i))))
#+END_SRC

** Archive mail

#+BEGIN_SRC elisp
(setq mu4e-refile-folder
      (lambda (msg)
        (cond
         ((string-match-p "lonyelon@gmail.com" (mu4e-message-field msg :maildir)) "/lonyelon@gmail.com/[Gmail]/Todos")
         ((string-match-p "yo@sergio.sh" (mu4e-message-field msg :maildir)) "/yo@sergio.sh/Archive")
         (t "/archive"))))
#+END_SRC

** Send mail

#+BEGIN_SRC elisp
(setq message-send-mail-function 'smtpmail-send-it)
(setq smtpmail-smtp-server "mail.sergio.sh"
      smtpmail-smtp-service 587
      smtpmail-stream-type 'starttls)
#+END_SRC

* Zen mode

#+BEGIN_SRC elisp
(add-hook 'writeroom-mode-hook
  (lambda ()
    (face-remap-add-relative 'default :family "Inter")))
(setq +zen-text-scale 0.6)
#+END_SRC

* Elfeed

#+BEGIN_SRC elisp
(map! :leader
      :desc "Open elfeed"
      "o n" #'elfeed)
(after! elfeed
  (setq elfeed-search-filter "@1-month-ago +unread -youtube")
  (add-hook! 'elfeed-search-mode-hook #'elfeed-update))
#+END_SRC

** Youtube
*** Open YouTube on MPV

#+BEGIN_SRC elisp
(after! elfeed
  (defun sergio/elfeed-open-entry ()
    "Open elfeed entry: mpv for youtube, browser for everything else"
    (interactive)
    (let ((entry (elfeed-search-selected :single)))
      (if (elfeed-tagged-p 'youtube entry)
          (progn
            (elfeed-untag entry 'unread)
            (elfeed-search-update-entry entry)
            (start-process "mpv" nil "mpv" (elfeed-entry-link entry)))
        (elfeed-search-browse-url))))
  (evil-define-key 'normal elfeed-search-mode-map
    (kbd "g o") #'sergio/elfeed-open-entry))
#+END_SRC

*** YouTube feed keybinding

#+BEGIN_SRC elisp
(defun sergio/open-youtube-elfeed ()
  (interactive)
  (elfeed)
  (elfeed-search-set-filter "+youtube"))
(map! :leader
      :desc "Open Youtube (elfeed)"
      "o y" #'sergio/open-youtube-elfeed)
#+END_SRC

* Dired

#+BEGIN_SRC elisp
(setq dired-omit-files "^\\..*")
(add-hook! dired-mode
  (evil-local-set-key 'normal (kbd "h") #'dired-omit-mode))
#+END_SRC

* Company mode

This is just so company help is only shown when presing =Ctrl+SPC= and not always. EMACS is single-threaded, can't wait for the lsp to process all my code.

#+BEGIN_SRC elisp
(after! company
  (setq company-idle-delay nil))
#+END_SRC

* Custom functions
** Theme switching

The idea is to call this from outside Emacs, when I switch between dark and light modes in my compositor.

#+BEGIN_SRC elisp
(defun sergio/toggle-theme ()
  "Toggle between dark and light themes"
  (interactive)
  (let ((current-theme (car custom-enabled-themes)))
    (mapc #'disable-theme custom-enabled-themes)
    (if (not (eq current-theme 'doom-1337))
        (progn
          (load-theme 'doom-1337 t)
          (message "Switched to dark theme (doom-1337)"))
      (progn
        (load-theme 'doom-gruvbox-light t)
        (message "Switched to light theme (doom-gruvbox-light)")))))
(map! :leader
      :desc "Switch between dark and light themes"
      "t t" #'sergio/toggle-theme)
#+END_SRC
